
server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/homeDeliveyApplication?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
    logging:  
     file:
       name : C:\Users\manda\OneDrive\Desktop\LMS 
     level:
        org:
         springframawork: info
         hibernate: error